# Generated by Django 3.1.1 on 2020-12-01 21:08

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='images',
            name='status',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=images.models.user_directory_path),
        ),
    ]
