# Generated by Django 3.1.1 on 2021-01-04 16:48

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201201_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=images.models.user_directory_path),
        ),
    ]
